"""
Game Generation AI Agent
=======================

AI agent responsible for generating game mechanics, levels, and rules
from video analysis data.
"""

import numpy as np
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum
import random
import json
from datetime import datetime


class GameGenre(Enum):
    """Supported game genres."""
    PLATFORMER = "platformer"
    SHOOTER = "shooter"
    PUZZLE = "puzzle"
    RACING = "racing"
    ADVENTURE = "adventure"
    ARCADE = "arcade"
    STRATEGY = "strategy"


class GameElementType(Enum):
    """Types of game elements."""
    PLAYER = "player"
    ENEMY = "enemy"
    PLATFORM = "platform"
    COLLECTIBLE = "collectible"
    OBSTACLE = "obstacle"
    BACKGROUND = "background"
    TRIGGER = "trigger"


@dataclass
class GameElement:
    """Represents a game element with properties."""
    element_type: GameElementType
    element_id: str
    x: float
    y: float
    width: float
    height: float
    properties: Dict = field(default_factory=dict)
    
    def to_dict(self) -> dict:
        return {
            'type': self.element_type.value,
            'id': self.element_id,
            'x': self.x,
            'y': self.y,
            'width': self.width,
            'height': self.height,
            'properties': self.properties
        }


@dataclass
class GameRule:
    """Represents a game rule or mechanic."""
    rule_id: str
    description: str
    condition: str
    action: str
    priority: int = 0


@dataclass
class GameLevel:
    """Represents a generated game level."""
    level_id: str
    name: str
    elements: List[GameElement]
    rules: List[GameRule]
    background: Optional[str] = None
    difficulty: float = 1.0
    estimated_duration: float = 60.0  # seconds
    
    def to_dict(self) -> dict:
        return {
            'level_id': self.level_id,
            'name': self.name,
            'elements': [e.to_dict() for e in self.elements],
            'rules': [
                {
                    'rule_id': r.rule_id,
                    'description': r.description,
                    'condition': r.condition,
                    'action': r.action,
                    'priority': r.priority
                } for r in self.rules
            ],
            'background': self.background,
            'difficulty': self.difficulty,
            'estimated_duration': self.estimated_duration
        }


@dataclass
class GameDesign:
    """Complete game design generated by AI."""
    game_id: str
    title: str
    genre: GameGenre
    levels: List[GameLevel]
    global_rules: List[GameRule]
    theme: str
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    metadata: Dict = field(default_factory=dict)
    
    def to_dict(self) -> dict:
        return {
            'game_id': self.game_id,
            'title': self.title,
            'genre': self.genre.value,
            'levels': [l.to_dict() for l in self.levels],
            'global_rules': [
                {
                    'rule_id': r.rule_id,
                    'description': r.description,
                    'condition': r.condition,
                    'action': r.action,
                    'priority': r.priority
                } for r in self.global_rules
            ],
            'theme': self.theme,
            'created_at': self.created_at,
            'metadata': self.metadata
        }


class GameAgent:
    """
    AI Agent for generating games from video analysis.
    
    Takes scene analysis data and generates playable game levels
    with appropriate mechanics, elements, and rules.
    """
    
    # Mapping from video objects to game elements
    OBJECT_TO_ELEMENT = {
        'person': GameElementType.PLAYER,
        'car': GameElementType.ENEMY,
        'truck': GameElementType.OBSTACLE,
        'bus': GameElementType.OBSTACLE,
        'bicycle': GameElementType.PLAYER,
        'motorcycle': GameElementType.ENEMY,
        'dog': GameElementType.ENEMY,
        'cat': GameElementType.COLLECTIBLE,
        'bird': GameElementType.COLLECTIBLE,
        'tree': GameElementType.PLATFORM,
        'chair': GameElementType.PLATFORM,
        'table': GameElementType.PLATFORM,
        'ball': GameElementType.COLLECTIBLE,
        'bottle': GameElementType.COLLECTIBLE,
        'cup': GameElementType.COLLECTIBLE,
    }
    
    # Scene type to genre mapping
    SCENE_TO_GENRE = {
        'urban': GameGenre.ARCADE,
        'nature': GameGenre.ADVENTURE,
        'indoor': GameGenre.PUZZLE,
        'empty': GameGenre.STRATEGY,
        'unknown': GameGenre.PLATFORMER
    }
    
    def __init__(self, agent_id: str = "game_agent_001", 
                 creativity: float = 0.7, 
                 difficulty_range: Tuple[float, float] = (0.5, 2.0)):
        """
        Initialize Game Agent.
        
        Args:
            agent_id: Unique agent identifier
            creativity: How creative the agent should be (0-1)
            difficulty_range: Min and max difficulty for generated levels
        """
        self.agent_id = agent_id
        self.creativity = creativity
        self.difficulty_range = difficulty_range
        self.generated_games: List[GameDesign] = []
        self.learning_data: List[Dict] = []
        
    def generate_game_from_scene(self, scene_analysis: dict, 
                                  num_levels: int = 3) -> GameDesign:
        """
        Generate a complete game from scene analysis data.
        
        Args:
            scene_analysis: Scene analysis dictionary from AIVision
            num_levels: Number of levels to generate
            
        Returns:
            GameDesign object
        """
        game_id = f"game_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        # Determine genre from scene
        scene_type = scene_analysis.get('scene_type', 'unknown')
        genre = self.SCENE_TO_GENRE.get(scene_type, GameGenre.PLATFORMER)
        
        # Generate theme
        theme = self._generate_theme(scene_analysis)
        
        # Generate levels
        levels = []
        for i in range(num_levels):
            level = self._generate_level(
                scene_analysis=scene_analysis,
                level_num=i+1,
                genre=genre,
                theme=theme
            )
            levels.append(level)
            
        # Generate global rules
        global_rules = self._generate_global_rules(genre)
        
        # Create game design
        game_design = GameDesign(
            game_id=game_id,
            title=f"{theme.replace(' ', '_')}_Game",
            genre=genre,
            levels=levels,
            global_rules=global_rules,
            theme=theme,
            metadata={
                'source_scene': scene_type,
                'agent_id': self.agent_id,
                'creativity': self.creativity
            }
        )
        
        self.generated_games.append(game_design)
        return game_design
        
    def _generate_level(self, scene_analysis: dict, 
                        level_num: int, 
                        genre: GameGenre,
                        theme: str) -> GameLevel:
        """Generate a single game level."""
        level_id = f"level_{level_num}"
        name = f"Level {level_num}"
        
        # Generate elements from detected objects
        elements = self._generate_elements(scene_analysis)
        
        # Add level-specific elements (pass existing to avoid duplicate player)
        elements.extend(self._generate_level_specific_elements(level_num, genre, existing=elements))
        
        # Generate rules
        rules = self._generate_level_rules(elements, genre)
        
        # Calculate difficulty
        difficulty = self.difficulty_range[0] + (self.difficulty_range[1] - self.difficulty_range[0]) * (level_num / 10.0)  # Scale with level number
        
        return GameLevel(
            level_id=level_id,
            name=name,
            elements=elements,
            rules=rules,
            background=theme,
            difficulty=difficulty,
            estimated_duration=60.0 + (level_num * 30)
        )
        
    def _generate_elements(self, scene_analysis: dict) -> List[GameElement]:
        """Generate game elements from scene objects."""
        elements = []
        objects = scene_analysis.get('objects', [])
        
        for obj in objects:
            element_type = self.OBJECT_TO_ELEMENT.get(
                obj.get('class_name', ''), 
                GameElementType.PLATFORM
            )
            
            # Convert bounding box to game coordinates
            x = obj['bbox'][0]
            y = obj['bbox'][1]
            width = obj['bbox'][2] - obj['bbox'][0]
            height = obj['bbox'][3] - obj['bbox'][1]
            
            element = GameElement(
                element_type=element_type,
                element_id=f"{element_type.value}_{len(elements)}",
                x=x,
                y=y,
                width=width,
                height=height,
                properties=self._generate_element_properties(element_type, obj)
            )
            elements.append(element)
            
        return elements
        
    def _generate_element_properties(self, element_type: GameElementType, 
                                      obj: dict) -> Dict:
        """Generate properties for a game element."""
        properties = {
            'speed': random.uniform(1, 5),
            'health': 100,
            'score_value': 10
        }
        
        if element_type == GameElementType.PLAYER:
            properties.update({
                'speed': random.uniform(3, 8),
                'jump_force': random.uniform(5, 12),
                'can_shoot': True
            })
        elif element_type == GameElementType.ENEMY:
            properties.update({
                'speed': random.uniform(2, 6),
                'damage': random.randint(10, 30),
                'aggression': random.uniform(0.5, 1.0)
            })
        elif element_type == GameElementType.COLLECTIBLE:
            properties.update({
                'score_value': random.randint(10, 100),
                'respawn_time': random.uniform(5, 15)
            })
        elif element_type == GameElementType.PLATFORM:
            properties.update({
                'is_moving': random.random() < 0.2,
                'move_speed': random.uniform(1, 3),
                'move_range': random.uniform(50, 200)
            })
            
        return properties
        
    def _generate_level_specific_elements(self, level_num: int, 
                                          genre: GameGenre, existing: List[GameElement] = None) -> List[GameElement]:
        """Generate level-specific elements. Checks existing so we don't duplicate player."""
        elements = []
        has_player = False
        if existing:
            has_player = any(e.element_type == GameElementType.PLAYER for e in existing)
        # also check elements itself (for solo call)
        has_player = has_player or any(e.element_type == GameElementType.PLAYER for e in elements)
        if not has_player:
            elements.append(GameElement(
                element_type=GameElementType.PLAYER,
                element_id="player_0",
                x=100,
                y=100,
                width=40,
                height=80,
                properties={'speed': 5, 'jump_force': 10}
            ))
            
        # Add genre-specific elements
        if genre == GameGenre.PLATFORMER:
            # Add platforms
            for i in range(3 + level_num):
                elements.append(GameElement(
                    element_type=GameElementType.PLATFORM,
                    element_id=f"platform_{i}",
                    x=200 + i * 150,
                    y=300 + random.uniform(-50, 50),
                    width=100 + random.uniform(0, 50),
                    height=20,
                    properties={'is_moving': random.random() < 0.3}
                ))
                
        elif genre == GameGenre.SHOOTER:
            # Add enemies
            for i in range(2 + level_num // 2):
                elements.append(GameElement(
                    element_type=GameElementType.ENEMY,
                    element_id=f"enemy_{i}",
                    x=400 + i * 200,
                    y=200 + random.uniform(-50, 50),
                    width=40,
                    height=60,
                    properties={'speed': random.uniform(2, 5), 'damage': 20}
                ))
                
        return elements
        
    def _generate_level_rules(self, elements: List[GameElement], 
                              genre: GameGenre) -> List[GameRule]:
        """Generate rules for a level."""
        rules = []
        
        # Common rules
        rules.append(GameRule(
            rule_id="rule_001",
            description="Player can move left and right",
            condition="player.input.left or player.input.right",
            action="player.velocity.x = player.input.direction * player.speed",
            priority=10
        ))
        
        rules.append(GameRule(
            rule_id="rule_002",
            description="Player can jump",
            condition="player.input.jump and player.is_grounded",
            action="player.velocity.y = -player.jump_force; player.is_grounded = False",
            priority=10
        ))
        
        rules.append(GameRule(
            rule_id="rule_003",
            description="Gravity affects player",
            condition="not player.is_grounded",
            action="player.velocity.y += gravity",
            priority=5
        ))
        
        # Genre-specific rules
        if genre == GameGenre.PLATFORMER:
            rules.append(GameRule(
                rule_id="rule_platform_001",
                description="Player can stand on platforms",
                condition="player.collides_with(platform) and player.velocity.y >= 0",
                action="player.is_grounded = True; player.y = platform.y - player.height",
                priority=20
            ))
            
        elif genre == GameGenre.SHOOTER:
            rules.append(GameRule(
                rule_id="rule_shooter_001",
                description="Player can shoot",
                condition="player.input.shoot",
                action="create_projectile(player.x, player.y, player.input.aim_direction)",
                priority=15
            ))
            
            rules.append(GameRule(
                rule_id="rule_shooter_002",
                description="Projectiles damage enemies",
                condition="projectile.collides_with(enemy)",
                action="enemy.health -= projectile.damage; destroy(projectile)",
                priority=20
            ))
            
        return rules
        
    def _generate_global_rules(self, genre: GameGenre) -> List[GameRule]:
        """Generate global game rules."""
        rules = [
            GameRule(
                rule_id="global_001",
                description="Game starts when player is ready",
                condition="player.ready",
                action="game.start()",
                priority=100
            ),
            GameRule(
                rule_id="global_002",
                description="Game over when player health reaches zero",
                condition="player.health <= 0",
                action="game.over()",
                priority=100
            ),
            GameRule(
                rule_id="global_003",
                description="Score increases when collecting items",
                condition="player.collides_with(collectible)",
                action="player.score += collectible.score_value; destroy(collectible)",
                priority=50
            )
        ]
        
        return rules
        
    def _generate_theme(self, scene_analysis: dict) -> str:
        """Generate game theme from scene analysis."""
        scene_type = scene_analysis.get('scene_type', 'unknown')
        objects = [obj.get('class_name', '') for obj in scene_analysis.get('objects', [])]
        colors = scene_analysis.get('dominant_colors', [])
        
        # Simple theme generation
        if scene_type == 'urban':
            return "City Adventure"
        elif scene_type == 'nature':
            return "Forest Explorer"
        elif scene_type == 'indoor':
            return "Mystery Mansion"
        else:
            # Use dominant object
            if objects:
                return f"{objects[0].title()} Quest"
            return "Mystery Game"
            
    def optimize_placement(self, elements: List[GameElement], 
                           frame_width: int, frame_height: int) -> List[GameElement]:
        """
        Optimize element placement for better gameplay.
        
        Args:
            elements: List of game elements
            frame_width: Width of the frame
            frame_height: Height of the frame
            
        Returns:
            Optimized list of elements
        """
        optimized = []
        
        for element in elements:
            # Ensure elements are within bounds
            x = max(0, min(element.x, frame_width - element.width))
            y = max(0, min(element.y, frame_height - element.height))
            
            # Add some randomness based on creativity
            if self.creativity > 0:
                x += random.uniform(-20, 20) * self.creativity
                y += random.uniform(-20, 20) * self.creativity
                
            optimized.append(GameElement(
                element_type=element.element_type,
                element_id=element.element_id,
                x=x,
                y=y,
                width=element.width,
                height=element.height,
                properties=element.properties
            ))
            
        return optimized
        
    def learn_from_feedback(self, game_id: str, feedback: dict):
        """
        Learn from user feedback to improve future generations.
        
        Args:
            game_id: ID of the game being rated
            feedback: Feedback dictionary with ratings and comments
        """
        self.learning_data.append({
            'game_id': game_id,
            'timestamp': datetime.now().isoformat(),
            'feedback': feedback
        })
        
        # Adjust creativity based on feedback
        if 'creativity' in feedback:
            self.creativity = max(0, min(1, self.creativity + feedback['creativity']))
            
    def save_game_design(self, game_design: GameDesign, 
                         filepath: str):
        """Save game design to JSON file."""
        with open(filepath, 'w') as f:
            json.dump(game_design.to_dict(), f, indent=2)
            
    def load_game_design(self, filepath: str) -> GameDesign:
        """Load game design from JSON file."""
        with open(filepath, 'r') as f:
            data = json.load(f)
            
        # Convert back to GameDesign object
        levels = [
            GameLevel(
                level_id=l['level_id'],
                name=l['name'],
                elements=[
                    GameElement(
                        element_type=GameElementType(e['type']),
                        element_id=e['id'],
                        x=e['x'],
                        y=e['y'],
                        width=e['width'],
                        height=e['height'],
                        properties=e['properties']
                    ) for e in l['elements']
                ],
                rules=[
                    GameRule(
                        rule_id=r['rule_id'],
                        description=r['description'],
                        condition=r['condition'],
                        action=r['action'],
                        priority=r['priority']
                    ) for r in l['rules']
                ],
                background=l.get('background'),
                difficulty=l.get('difficulty', 1.0),
                estimated_duration=l.get('estimated_duration', 60.0)
            ) for l in data['levels']
        ]
        
        global_rules = [
            GameRule(
                rule_id=r['rule_id'],
                description=r['description'],
                condition=r['condition'],
                action=r['action'],
                priority=r['priority']
            ) for r in data['global_rules']
        ]
        
        return GameDesign(
            game_id=data['game_id'],
            title=data['title'],
            genre=GameGenre(data['genre']),
            levels=levels,
            global_rules=global_rules,
            theme=data['theme'],
            created_at=data.get('created_at', ''),
            metadata=data.get('metadata', {})
        )
